;; Private stdin -> fd 3 protocol, never eval. The parent is intentionally kept
;; BEFORE ly:reset-all-fonts / declarations-init.ly: Pango may start threads.
;; Every request forks; score Scheme, options, fonts and sessions die with it.
(define preview-control (fdopen 3 "w"))
(unless (and (equal? (lilypond-version) "2.26.0")
             (defined? 'primitive-fork)
             lily-preview-cache-installed?)
  (primitive-exit 2))
(display "READY\n" preview-control)
(force-output preview-control)
(let loop ()
  (let ((request (read)))
    (unless (eof-object? request)
      (unless (and (list? request) (= (length request) 3)
                   (integer? (car request))
                   (string? (cadr request)) (string? (caddr request)))
        (primitive-exit 2))
      (let ((pid (primitive-fork)))
        (if (= pid 0)
            (begin
              (close-port preview-control)
              (close-port (current-input-port))
              (let ((input (open-input-file "/dev/null")))
                (dup2 (fileno input) 0)
                (set-current-input-port input))
              (chdir (caddr request))
              (ly:stderr-redirect "worker.stderr" "w")
              (let ((out (open-output-file "worker.stdout")))
                (dup2 (fileno out) 1)
                (set-current-output-port out)
                (let ((failed (lilypond-all (list (cadr request)))))
                  (flush-all-ports)
                  (primitive-exit (if (null? failed) 0 1)))))
            (let* ((status (cdr (waitpid pid)))
                   (code (status:exit-val status)))
              (format preview-control "DONE ~a ~a\n" (car request) (or code -1))
              (force-output preview-control))))
      (loop))))
(primitive-exit 0)
